#
# Required Pipeline Variables:
#
# - SUFFIX
# - RESOURCE_GROUP_LOCATION
# - SHARED_SERVICES_VNET_NAME
# - SHARED_SERVICES_RESOURCE_GROUP_NAME

trigger: none

stages:
  - stage: CD
    jobs:

    - job: CD
      pool: SharedServices
      workspace:  
        clean: all
      container:
        image: ssbuild-dev
        endpoint: acr-shared-services
      
      steps:
        - checkout: self
        - task: AzureCLI@2
          name: AzCreds
          displayName: Get Azure Credentials
          inputs:
              azureSubscription: rm-shared-services
              scriptType: bash
              addSpnToEnvironment: true
              scriptLocation: inlineScript
              inlineScript: |
                echo '##vso[task.setvariable variable=AZ_SPN;isOutput=true]'$servicePrincipalId
                echo '##vso[task.setvariable variable=AZ_SPN_KEY;isOutput=true]'$servicePrincipalKey
                echo '##vso[task.setvariable variable=AZ_TENANT;isOutput=true]'$tenantId
                AZ_SUB_ID=`az account show -o tsv | awk '{ print $3 }'`
                echo '##vso[task.setvariable variable=AZ_SUB_ID;isOutput=true]'$AZ_SUB_ID


        - bash: ./scripts/automation/shared_services-cd.sh 
          workingDirectory: .
          displayName: 'Deploy TF Backend'
          env:
            ARM_CLIENT_ID: $(AzCreds.AZ_SPN)
            ARM_CLIENT_SECRET: $(AzCreds.AZ_SPN_KEY)
            ARM_SUBSCRIPTION_ID: $(AzCreds.AZ_SUB_ID)
            ARM_TENANT_ID: $(AzCreds.AZ_TENANT)
            TF_VAR_suffix: $(SUFFIX)
            TF_VAR_resource_group_location: $(RESOURCE_GROUP_LOCATION)
            TF_VAR_shared_services_virtual_network_name: $(SHARED_SERVICES_VNET_NAME) 
            TF_VAR_shared_services_virtual_network_resource_group_name: $(SHARED_SERVICES_RESOURCE_GROUP_NAME)
