#
# Required Pipeline Variables:
#
# - SUFFIX
# - RESOURCE_GROUP_LOCATION
# - SHARED_SERVICES_VNET_NAME
# - SHARED_SERVICES_RESOURCE_GROUP_NAME
# - AZURE_DEVOPS_ORGANISATION
# - AZURE_DEVOPS_PROJECT
# - AZURE_DEVOPS_PAT

trigger: none

variables:
- name: DOCKER_REGISTRY_SERVICE_CONNECTION
  value: acr-shared-services 
- name: DOCKER_IMAGE_NAME
  value: ssbuild-dev

jobs:

- job: DockerCI

  pool: SharedServices

  steps:
  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: acr-shared-services

  - bash: scripts/automation/docker-ci.sh
    displayName: 'Docker CI'
    env:
      DOCKER_REGISTRY_URL: acrdevss$(SUFFIX).azurecr.io
      DOCKERFILE_PATH: ".devcontainer/Dockerfile"
      DOCKER_IMAGE_NAME: $(DOCKER_IMAGE_NAME)


- job: TerraformCI

  dependsOn: DockerCI

  pool: SharedServices

  container:
    image: $(DOCKER_IMAGE_NAME)
    endpoint: acr-shared-services

  steps:
  - task: AzureCLI@2
    name: AzCreds
    displayName: Get Azure Credentials
    inputs:
        azureSubscription: rm-shared-services
        scriptType: bash
        addSpnToEnvironment: true
        scriptLocation: inlineScript
        inlineScript: |
          echo '##vso[task.setvariable variable=AZ_SPN;isOutput=true]'$servicePrincipalId
          echo '##vso[task.setvariable variable=AZ_SPN_KEY;isOutput=true]'$servicePrincipalKey
          echo '##vso[task.setvariable variable=AZ_TENANT;isOutput=true]'$tenantId
          AZ_SUB_ID=`az account show -o tsv | awk '{ print $3 }'`
          echo '##vso[task.setvariable variable=AZ_SUB_ID;isOutput=true]'$AZ_SUB_ID


  - bash: ./scripts/automation/shared_services-ci.sh
    workingDirectory: .
    displayName: 'Terraform CI'
    env: 
      ARM_CLIENT_ID: $(AzCreds.AZ_SPN)
      ARM_CLIENT_SECRET: $(AzCreds.AZ_SPN_KEY)
      ARM_SUBSCRIPTION_ID: $(AzCreds.AZ_SUB_ID)
      ARM_TENANT_ID: $(AzCreds.AZ_TENANT)
      TF_VAR_suffix: $(SUFFIX)
      TF_VAR_resource_group_location: $(RESOURCE_GROUP_LOCATION)
      TF_VAR_shared_services_virtual_network_name: $(SHARED_SERVICES_VNET_NAME) 
      TF_VAR_shared_services_virtual_network_resource_group_name: $(SHARED_SERVICES_RESOURCE_GROUP_NAME)
      TF_VAR_azure_devops_organisation: $(AZURE_DEVOPS_ORGANISATION)
      TF_VAR_azure_devops_project: $(AZURE_DEVOPS_PROJECT)
      TF_VAR_azure_devops_pat: $(AZURE_DEVOPS_PAT)
      
